name: extended
description: A set of handy widgets and functions that are extended based on Material and Cupertino widgets.
version: 0.0.7
homepage: https://github.com/thruthesky/extended

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

